### ISSUE TITLE
Plugin doesn't respect line_length

### ISSUE THREAD

**Issue by GRoguelon** [angelikatyborska/doctest_formatter#28]
Hi Angelika,

Thank you very much for the plugin, I can't count the number of times I copied and pasted the doctests in a Elixir file to format and put it back in comments. 

I was installing this plugin in one of our project in my company and potentially identified an issue. From what I see I think the plugin is not respecting the `line_length` configuration.

Before installing the plugin, `mix format` was changing nothing. After installing it almost changed all the project files and from the Git diff it is almost exclusively changing line length to make it back to 98ish characters while the project is configured to **120**.

I have created a repo to reflect it [GRoguelon/doctest_formatter_line_length](https://github.com/GRoguelon/doctest_formatter_line_length). You can see the effect of the plugin as shown [here](https://github.com/GRoguelon/doctest_formatter_line_length/commit/f5e290374e43dcae9a23003ca6edcde2354202ed).

There is a branch [doctest_formatter](https://github.com/GRoguelon/doctest_formatter_line_length/tree/doctest_formatter) with the changes.

Please let me know if you need any additional information.

**Comment by angelikatyborska** [comment]
Thank you for the report and thank you so much for the reproduction repository 💚 💙 💜  you're the best.

You're right that there is a bug with the plugin not respecting line length when it formats the whole Elixir file! I'm about to release version 0.3.1 with a fix.

**Comment by angelikatyborska** [comment]
Released: https://hex.pm/packages/doctest_formatter/0.3.1
